project:
  type: seedcase-theme

website:
  title: "Seedcase Project: Decisions Archive"
  site-url: "https://decisions.seedcase-project.org/"
  repo-url: "https://github.com/seedcase-project/decisions"
  navbar:
    title: false
    logo: _extensions/seedcase-project/seedcase-theme/logos/docs/navbar-decisions.svg
    logo-alt: "Seedcase Decisions logo: Main page"
    pinned: true
    search: true
    left:
      - current.qmd
      - previous.qmd
    tools:
      - icon: house
        href: "https://seedcase-project.org"
        aria-label: "House icon: Seedcase Project home page"
      - icon: github
        href: "https://github.com/seedcase-project/decisions"
        aria-label: "GitHub icon: Source code"

format:
  seedcase-theme-html:
    include-before-body:
      - "includes/site-counter.html"
